services:
  # ============================================
  # Base de données PostgreSQL
  # ============================================
  db:
    image: postgres:16-alpine
    container_name: secureapp_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: secureapp
      POSTGRES_PASSWORD: secureapp
      POSTGRES_DB: secureapp
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev_net

  # ============================================
  # Adminer (interface web pour PostgreSQL)
  # ============================================
  adminer:
    image: adminer:latest
    container_name: secureapp_adminer_dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - dev_net

# ============================================
# Volumes persistants
# ============================================
volumes:
  db_data_dev:

# ============================================
# Réseaux
# ============================================
networks:
  dev_net: